# Generated by Django 3.2.9 on 2021-12-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_status',
            field=models.CharField(choices=[('OPEN', 'ACTIVE'), ('CLOSED', 'INACTIVE')], default='OPEN', max_length=6),
        ),
    ]
