# Generated by Django 3.2.9 on 2022-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_image',
            field=models.URLField(max_length=500),
        ),
    ]
